---
title: "core functions"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
if(!rlang::is_installed('cubar')){
  devtools::install_github("mt1022/cubar", dependencies = TRUE)
}

suppressPackageStartupMessages(library(Biostrings))
library(cubar)
library(tidyverse)
library(GGally)
```

### Quality of input CDS
```{r}
yeast_cds  # CDSs of all yeast protein-coding genes

# check and exclude CDSs that:
# - do not have a length dividable by 3;
# - are incomplete (e.g., missing start or stop codon);
# - contain internal stop codons;
# Then, remove start and stop codons from the remaining CDSs.
yeast_cds_qc <- check_cds(yeast_cds)
yeast_cds_qc

# get codon frequency matrix
yeast_cf <- count_codons(yeast_cds_qc)
```

### Calculate core codon usage bias metrics
```{r}
yeast_exp <- yeast_exp |> 
    filter(gene_id %in% rownames(yeast_cf))

# get highly- and lowly-expressed genes
yeast_heg <- yeast_exp |> slice_max(fpkm, n = 500)
yeast_leg <- yeast_exp |> slice_min(fpkm, n = 500)

# RSCU of highly-expressed genes will be used for CAI calculation
yeast_rscu <- est_rscu(yeast_cf[yeast_heg$gene_id, ])

# tRNA weights for calculating TAI
yeast_trna_w <- est_trna_weight(yeast_trna_gcn)

# estimate optimal codons based on gene expression levels
yeast_opt_codons <- est_optimal_codons(
    yeast_cf[yeast_exp$gene_id, ],
    gene_score = log1p(yeast_exp$fpkm))
yeast_opt_codons <- yeast_opt_codons |>
    filter(optimal == TRUE) |>
    pull(codon)

# codon stabilization coefficient for calculating CSCg
tmp <- intersect(rownames(yeast_cf), yeast_half_life$gene_id)
yeast_half_life <- yeast_half_life |> filter(gene_id %in% tmp)
yeast_csc <- est_csc(yeast_cds_qc[yeast_half_life$gene_id], yeast_half_life)


yeast_cub <- tibble(
    gene_id = rownames(yeast_cf),
    enc = get_enc(yeast_cf),
    cai = get_cai(yeast_cf, rscu = yeast_rscu),
    tai = get_tai(yeast_cf, trna_w = yeast_trna_w),
    fop = get_fop(yeast_cf, op = yeast_opt_codons),
    gc3s = get_gc3s(yeast_cf),
    cscg = get_cscg(yeast_cf, csc = yeast_csc)
)

scatter_hexbin <- function(data, mapping, ...) {
  ggplot(data = data, mapping = mapping) +
    geom_hex(...) +
    scale_fill_viridis_c(transform = 'log1p')
}

yeast_cub |> 
    select(ENC = enc, CAI = cai, tAI = tai, Fop = fop, GC3s = gc3s, CSCg = cscg) |>
    ggpairs(lower = list(continuous = scatter_hexbin)) +
    theme_minimal(base_size = 12) +
    theme(axis.text = element_text(color = 'black'), 
          axis.text.x = element_text(angle = 50, hjust = 1))
ggsave('figures/yeast_cub_indices.pdf', width = 11, height = 8)
```

Relationship between CUB indices and gene expression levels and mRNA stability
```{r}
yeast_cub_exp <- yeast_cub |> 
    inner_join(yeast_exp, by = 'gene_id') |>
    select(gene_id, ENC = enc, CAI = cai, tAI = tai, Fop = fop, GC3s = gc3s, CSCg = cscg, fpkm) |> 
    pivot_longer(-c(gene_id, fpkm), names_to = 'index', values_to = 'value')

ggplot(yeast_cub_exp, aes(x = fpkm, y = value)) +
    geom_hex(show.legend = FALSE) +
    scale_fill_viridis_c(transform = 'log1p', breaks = c(1, 10, 100)) +
    scale_x_continuous(transform = 'log1p', breaks = c(1, 10, 100, 1000, 10000)) +
    facet_grid(rows = vars(index), scales = 'free_y') +
    labs(x = 'Expression level (RPKM)', y = 'Codon usage index') +
    theme_bw(base_size = 12) +
    theme(axis.text = element_text(color = 'black'))
ggsave('figures/yeast_cub_indices_vs_expression.pdf', width = 2.5, height = 8)

yeast_cub_hlife <- yeast_cub |> 
    inner_join(yeast_half_life, by = 'gene_id') |>
    select(gene_id, ENC = enc, CAI = cai, tAI = tai, Fop = fop, GC3s = gc3s, CSCg = cscg, half_life) |> 
    pivot_longer(-c(gene_id, half_life), names_to = 'index', values_to = 'value')

ggplot(yeast_cub_hlife, aes(x = half_life, y = value)) +
    geom_hex(show.legend = FALSE) +
    scale_fill_viridis_c(transform = 'log1p', breaks = c(1, 10, 100)) +
    scale_x_continuous(transform = 'log2', breaks = c(2, 4, 8, 16, 32, 64)) +
    facet_grid(rows = vars(index), scales = 'free_y') +
    labs(x = 'Half-life (minute)', y = 'Codon usage index') +
    theme_bw(base_size = 12) +
    theme(axis.text = element_text(color = 'black'))
ggsave('figures/yeast_cub_indices_vs_halflife.pdf', width = 2.5, height = 8)
```

